---
- name: Create temporary directory
  hosts: all
  gather_facts: true

  tasks:
    - name: Create temporary directory
      tempfile:
        state: directory
        prefix: temp_directory_
        dir: "~"
      register: temp_dir

    - name: Display temporary directory path
      debug:
        var: temp_dir.path
