---
- name: Create temporary directory
  hosts: all
  gather_facts: true

  tasks:
    - name: Create temporary directory
      file:
        state: directory
        path: "{{ ansible_env.HOME }}/temp_directory_{{ ansible_date_time.epoch }}"
      register: temp_dir

    - name: Display temporary directory path
      debug:
        var: temp_dir.path
