---
- name: Create temporary directory
  hosts: 10.32.23.190
  gather_facts: false

  tasks:
    - name: Create temporary directory
      tempfile:
        state: directory
        prefix: temp_directory_
        dir: "{{ ansible_user_dir }}"
      register: temp_dir

    - name: Display temporary directory path
      debug:
        var: temp_dir.path
