---
- hosts: all
  gather_facts: true
  tasks:
    - debug:
        msg: "{{ morpheus | to_json }}"
        #msg: "{{ morpheus['morpheus']}}"
        #msg: "{{ morpheus['accountNumber'] }}"
        #msg: "User: {{ morpheus['user']['linuxUsername'] }}, Cloud Code: {{ morpheus['cloudCode'] }}"
        #msg: "{{ morpheus['instance']['container']['server']['internalIp'] }}"
        #msg: "{{ morpheus['instance']['container']['server']['osType'] }}"
