---
- name: Post Build Configuration for Windows Servers
  hosts: windows
  gather_facts: false
  tasks:
    - name: Define variable
      debug:
        msg: "{{ hostname | lower  }}"
    - name: Create IT Scripts directory
      win_file:
        path: c:\IT\Scripts
        state: directory
    - name: Disable inherited ACE's for c:\IT folder
      win_acl_inheritance:
        path: C:\IT
        state: absent
    - name: Add Administrators Group allow rights
      win_acl:
        path: C:\IT
        user: Administrators
        rights: FullControl
        type: allow
        state: present
        inherit: ContainerInherit, ObjectInherit
        propagation: 'InheritOnly'
    - name: Add SYSTEM Group allow rights
      win_acl:
        path: C:\IT
        user: SYSTEM
        rights: FullControl
        type: allow
        state: present
        inherit: ContainerInherit, ObjectInherit
        propagation: 'InheritOnly'
    - name: Add Power Users Group allow rights
      win_acl:
        path: C:\IT
        user: 'power users'
        rights: READ
        type: allow
        state: present
        inherit: ContainerInherit, ObjectInherit
        propagation: 'InheritOnly'
    - name: Create temp directory
      win_file:
        path: C:\Temp
        state: directory
    - name: Change CD-Rom Drive letter to Z
      win_shell: |
        $CDDrive = Get-WmiObject win32_volume | where {$_.DriveType -eq 5}
        if ($CDDrive  -ne $null) {
            $CDDrive.DriveLetter = "Z:";
            $CDDrive.put()
        }
    - name: Extend C Drive
      win_shell: |
        $cDriveSupportSize = $(Get-PartitionSupportedSize -DriveLetter "C").sizeMax
        $cDriveSize = $(Get-Partition -DriveLetter "C").size
        try{
            if($cDriveSupportSize -gt $cDriveSize)
            {
                resize-Partition -Size $cDriveSupportSize -DriveLetter "C" -ErrorAction stop
            }
        }
        catch{}
    - name: Remove all current pagefiles, enable AutomaticManagedPagefile and query at the end  
      win_pagefile:
        automatic: yes
    - name: Enable firewall for Domain, Public and Private profiles
      win_firewall:
        state: enabled
    - name: Add a local and domain user to a local group  
      win_group_membership:
        name: Administrators
        members:
          - 'XXXXXXXX\XXXXXXXXX'
          - 'XXXXXXXX\XXXXXXXXX'
        state: present
    - name: Download ndtrack.ps1
      win_get_url:
        url: "{{ windows_repo.url }}/flexera2018R2/ndtrack.ps1"
        dest: "C:\\temp\\ndtrack.ps1"
        force: True
    - name: Install Flexnet Inventory Agent from msi
      win_package:
        path: "{{ windows_repo.url }}/flexera2018R2/FlexNet_Inventory_Agent.msi"
        product_id: '{7A62397D-66E2-41C4-BFFC-2EBB38D16790}'
        arguments: /qn /norestart ALLUSERS=1 REBOOT=ReallySuppress /L*v c:\temp\FlexNet_Inventory_Agent_Installation.log
        state: present
    - name: Trigger ndtrack.ps1
      win_shell: "C:\\temp\\ndtrack.ps1"
      args:
        chdir: C:\\temp
